config/routes.rb
Klimaserver::Application.routes.draw do
  
  resources :votes

  resources :usersevents

  resources :events

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/addusertoevent', :to => 'events#addusertoevent'

end

app/models/usersevent.rb
class Usersevent < ActiveRecord::Base
  attr_accessible :user_id, :event_id, :admin
  
  belongs_to :event  # foreign key - programmer_id
  belongs_to :user
end

app/controllers/usersevents_controller.rb
class UserseventsController < ApplicationController
  # GET /usersevents
  # GET /usersevents.json
  def index
    @usersevents = Usersevent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @usersevents }
    end
  end

  # GET /usersevents/1
  # GET /usersevents/1.json
  def show
    @usersevent = Usersevent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @usersevent }
    end
  end

  # GET /usersevents/new
  # GET /usersevents/new.json
  def new
    @usersevent = Usersevent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @usersevent }
    end
  end

  # GET /usersevents/1/edit
  def edit
    @usersevent = Usersevent.find(params[:id])
  end

  # POST /usersevents
  # POST /usersevents.json
  def create
    @usersevent = Usersevent.new(params[:usersevent])

    respond_to do |format|
      if @usersevent.save
        format.html { redirect_to @usersevent, :notice => 'Usersevent was successfully created.' }
        format.json { render :json => @usersevent, :status => :created, :location => @usersevent }
      else
        format.html { render :action => "new" }
        format.json { render :json => @usersevent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /usersevents/1
  # PUT /usersevents/1.json
  def update
    @usersevent = Usersevent.find(params[:id])

    respond_to do |format|
      if @usersevent.update_attributes(params[:usersevent])
        format.html { redirect_to @usersevent, :notice => 'Usersevent was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @usersevent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /usersevents/1
  # DELETE /usersevents/1.json
  def destroy
    @usersevent = Usersevent.find(params[:id])
    @usersevent.destroy

    respond_to do |format|
      format.html { redirect_to usersevents_url }
      format.json { head :ok }
    end
  end
end

app/helpers/usersevents_helper.rb
module UserseventsHelper
end

app/views/usersevents/_form.html.erb
<%= form_for(@usersevent) do |f| %>
  <% if @usersevent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usersevent.errors.count, "error") %> prohibited this usersevent from being saved:</h2>

      <ul>
      <% @usersevent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.text_field :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usersevents/edit.html.erb
<h1>Editing usersevent</h1>

<%= render 'form' %>

<%= link_to 'Show', @usersevent %> |
<%= link_to 'Back', usersevents_path %>

app/views/usersevents/index.html.erb
<h1>Listing usersevents</h1>

<table>
  <tr>
    <th>Event</th>
    <th>User</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usersevents.each do |usersevent| %>
  <tr>
    <td><%= usersevent.event_id %></td>
    <td><%= usersevent.user_id %></td>
    <td><%= usersevent.admin %></td>
    <td><%= link_to 'Show', usersevent %></td>
    <td><%= link_to 'Edit', edit_usersevent_path(usersevent) %></td>
    <td><%= link_to 'Destroy', usersevent, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usersevent', new_usersevent_path %>

app/views/usersevents/new.html.erb
<h1>New usersevent</h1>

<%= render 'form' %>

<%= link_to 'Back', usersevents_path %>

app/views/usersevents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @usersevent.event_id %>
</p>

<p>
  <b>User:</b>
  <%= @usersevent.user_id %>
</p>

<p>
  <b>Admin:</b>
  <%= @usersevent.admin %>
</p>


<%= link_to 'Edit', edit_usersevent_path(@usersevent) %> |
<%= link_to 'Back', usersevents_path %>